jobs:
  - name: dv-man-qhs
    type: manifest
    steps:
      - IN: dv-image-qhs
        pull: false
      - IN: dv-opts-qhs
      - IN: dv-params-qhs
       
    on_success:
      - echo 'this is on_success step of dv-man of type manifest'
    on_failure:
      - echo 'this is on_failure step of dv-man of type manifest'

  
